name: Deploy all files statically to github pages
on:
  push:
    branches: main

jobs:
  deploy:
    name: Build site and pdfs
    runs-on: ubuntu-18.04
    steps:
      - name: Install dependencies
        run:  |
          sudo apt update
          sudo apt install texlive-latex-extra texlive-lang-italian texlive-lang-english texlive-fonts-recommended texlive-bibtex-extra texlive-science latexmk libreoffice wget curl make rsync git
          curl -sf https://goblin.reaper.im/github.com/lucat1/statik | sudo sh
          wget https://github.com/jgm/pandoc/releases/download/2.18/pandoc-2.18-linux-amd64.tar.gz -O /tmp/pandoc.tar.gz
          tar xfz /tmp/pandoc.tar.gz -C /tmp
          sudo mv /tmp/pandoc-*/bin/* /usr/bin

      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      
      - name: Recursively compile tex files
        run: ./.github/workflows/rec "*\.tex$" "latexmk -pdf"

      - name: Recursively compile (doc|ppt)x? files
        run: ./.github/workflows/rec "*\.(doc|ppt)x?$" "libreoffice --headless --convert-to pdf --outdir ."

      - name: Recursively compile md files
        run: ./.github/workflows/rec "*\.md$" ${GITHUB_WORKSPACE}/.github/workflows/md2pdf

      - name: Generate static directory listing
        run: statik -l -b "https://${{ github.event.repository.owner.name }}.github.io/${{ github.event.repository.name }}/" -i "\.(pdf|link|txt)$" -e "\.git(hub|ignore|keep)?"

      - name: Deploy to Pages
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages
          folder: site
